SES.Web/Controllers/TestingController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SES.Domain.Entity.TestE;
using SES.Service.Interfaces;
using System.Linq;
using System.Text.Json;

namespace SES.Web.Controllers
{
	public class TestingController : Controller
	{
		private readonly ITestService _testService;
		private readonly ITestHistoryService _historyService;


		public TestingController(ITestService testService, ITestHistoryService historyService)
		{
			_testService = testService;
			_historyService = historyService;
		}

		[HttpGet]
		public async Task<IActionResult> GetTest(int test_ID)
		{
			var response = await _testService.Get(test_ID);
			if (response.StatusCode == Domain.Enum.ResponseStatus.Success)
			{
				return PartialView("_StartingPartialView", response.Data);
			}
			return BadRequest(response.Description);
		}

		[HttpGet]
		public async Task<IActionResult> TestStarting(int test_ID)
		{
			Random rng = new();
			HttpContext.Session.Clear();

			var response = await _testService.Get(test_ID);
			if (response.StatusCode == Domain.Enum.ResponseStatus.Success)
			{
				response.Data.Questions?.ForEach(x =>
				{
					x.Test = null;
					x.Options?.ForEach(d => d.Question = null);
				});

				var questions = response.Data.Questions?.OrderBy(x => rng.Next()).ToList();
				foreach (var question in questions)
				{
					question.Options = question.Options?.OrderBy(x => rng.Next()).ToList();
				}
				int i = 1;

				HttpContext.Session.SetString("Question.Count", questions.Count.ToString());
				HttpContext.Session.SetString("Test_ID", test_ID.ToString());
				HttpContext.Session.SetString("CurrentIndex", "1");
				foreach (var item in questions)
				{
					HttpContext.Session.SetString("Question[" + i++.ToString() + "]", JsonSerializer.Serialize(item));
				}

				ViewBag.Number = "1" + "/" + questions.Count.ToString();
				return PartialView("_TestingQusetionPartialView", questions.First());
			}
			return BadRequest(response.Description);
		}

		[HttpGet]
		public async Task<IActionResult> NextQuestion(string answer_option_ID, string status)
		{
			if (int.TryParse(HttpContext.Session.GetString("CurrentIndex"), out int current_index))
			{
				HttpContext.Session.SetString($"UserAnswer[{current_index}]", answer_option_ID);

				if (status == "Finish") return await FinishTesting();

				var question_string = HttpContext.Session.GetString($"Question[{++current_index}]");

				if (question_string != null)
				{
					var question = JsonSerializer.Deserialize<Question>(question_string);
					if (question != null)
					{

						HttpContext.Session.SetString("CurrentIndex", (current_index).ToString());
						ViewBag.Number = HttpContext.Session.GetString("CurrentIndex") + "/" + HttpContext.Session.GetString("Question.Count");
						ViewBag.Answer = HttpContext.Session.GetString($"UserAnswer[{current_index}]");
						return PartialView("_TestingQusetionPartialView", question);
					}
					else return BadRequest("Не вдалось десерелізувати питання");
				}
				else return BadRequest("Не вдалось зчитати питання");

			}
			return BadRequest("Не вдалось зчитати номер питання");

		}

		[HttpGet]
		public async Task<IActionResult> PreviousQuestion()
		{
			if (int.TryParse(HttpContext.Session.GetString("CurrentIndex"), out int current_index))
			{
				var question_string = HttpContext.Session.GetString($"Question[{--current_index}]");

				if (question_string != null)
				{
					var question = JsonSerializer.Deserialize<Question>(question_string);
					if (question != null)
					{
						HttpContext.Session.SetString("CurrentIndex", (current_index).ToString());

						ViewBag.Number = HttpContext.Session.GetString("CurrentIndex") + "/" + HttpContext.Session.GetString("Question.Count");
						ViewBag.Answer = HttpContext.Session.GetString($"UserAnswer[{current_index}]");
						return PartialView("_TestingQusetionPartialView", question);
					}
					else return BadRequest("Не вдалось десерелізувати питання");
				}
				else return BadRequest("Не вдалось зчитати питання");

			}
			return BadRequest("Не вдалось зчитати номер питання");

		}

		[HttpGet]
		public async Task<IActionResult> FinishTesting()
		{
			var right_answers = new List<string>();
			var user_answers = new List<string>();
			var Question_Count = HttpContext.Session.GetString("Question.Count");

			if (Question_Count != null)
			{
				for (int i = 1; i <= int.Parse(Question_Count); i++)
				{
					var question_string = HttpContext.Session.GetString($"Question[{i}]");
					if (question_string != null)
					{
						var question = JsonSerializer.Deserialize<Question>(question_string);
						if (question != null)
						{
							var _ = question.Options?.Where(x => x.Right == true).Select(x => x.Option_ID.ToString());
							right_answers.Add(string.Join(',', _));
						}
						else return BadRequest("Не вдалось десерелізувати питання");
					}
					else return BadRequest("Не вдалось зчитати питання");
				}
			}
			else return BadRequest("Не вдалось зчитати кількість питань");

			for (int i = 1; i <= int.Parse(Question_Count); i++)
			{
				var answer_string = HttpContext.Session.GetString($"UserAnswer[{i}]");
				if (answer_string != null)
				{
					user_answers.Add(answer_string);
				}
				else break;

			}

			double totalScore = 0;

			for (int i = 0; i < user_answers.Count; i++)
			{
				var r_answer = right_answers[i].Split(',');
				var u_answer = user_answers[i].Split(',');
				double scorePerAnswer = 1.0 / r_answer.Length;
				var user_score = 0.0;
				if (u_answer.Length >= r_answer.Length)
				{
					for (int j = 0; j < u_answer.Length; j++)
					{
						if (r_answer.Contains(u_answer[j]))
						{
							user_score += scorePerAnswer;
						}
						else
						{
							user_score = 0;
							break;
						}

					}
				}

				totalScore += user_score;
			}

			var mark = 0;
			mark = (double)((totalScore * 100) / int.Parse(Question_Count)) switch
			{
				>= 90 => 5,
				>= 80 => 4,
				>= 70 => 3,
				>= 60 => 2,
				_ => 1,
			};

			ViewBag.QuestionCount = int.Parse(Question_Count);
			var Test_History = new Test_History()
			{
				Date = DateTime.Now.ToShortDateString(),
				Mark = mark,
				Right_Answer_Count = (int)totalScore,
				Status = mark <= 2 ? Domain.Enum.ResultStatus.Fail : Domain.Enum.ResultStatus.Pass,
				Test_ID = int.Parse(HttpContext.Session.GetString("Test_ID")),
				User_ID = int.Parse(HttpContext.User.FindFirst("UserID").Value)
			};

			var response = await _historyService.Create(Test_History);
			if (response.StatusCode == Domain.Enum.ResponseStatus.Success)
			{
				return PartialView("_TestResultPartialView", Test_History);
			}
			else return BadRequest(response.Description);
			
		}

	}
}

SES.Web/Controllers/UserController.cs
using AutoMapper;
using Azure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SES.Domain.Entity.AbstractE;
using SES.Domain.Entity.UserE;
using SES.Domain.Enum;
using SES.Domain.ViewModel;
using SES.Service.Implementations;
using SES.Service.Interfaces;
using SES.Web.Models;
using System.Diagnostics;
using System.Text.Json;

namespace SES.Web.Controllers
{
	[Authorize]
	public class UserController : Controller
	{
		private readonly IUserService _userService;
		private readonly IMapper _mapper;
		private readonly ISelectService _selectService;

		public UserController(IUserService userService, IMapper mapper, ISelectService selectService)
		{
			_userService = userService;
			_mapper = mapper;
			_selectService = selectService;
		}

		[HttpGet]
		public IActionResult Index() => View();

		[HttpGet]
		public async Task<IActionResult> Profile()
		{
			var response = await _userService.Get(int.Parse(HttpContext.User.FindFirst("UserID").Value));
			if (response.StatusCode == ResponseStatus.Success)
			{
				return PartialView("_UserProfilePartialView", response.Data);
			}
			return View("ErrorView", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}

		[HttpPost]
		public async Task<IActionResult> Profile(User user)
		{
			var response = await _userService.Update(user);
			if (response.StatusCode == ResponseStatus.Success)
			{
				return Ok();
			}
			return BadRequest(response.Description);
		}

		[HttpGet]
		public async Task<IActionResult> GetUsersList()
		{
			var response = await _userService.Get();
			if (response.StatusCode == ResponseStatus.Success)
			{
				return PartialView("_UserListPartialView", response.Data);
			}
			return View("ErrorView", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}

		[HttpGet]
		public async Task<IActionResult> GetUsersListByName(string pib)
		{
			var response = await _userService.Get();
			if (response.StatusCode == ResponseStatus.Success)
			{
				if (pib == null) return PartialView("_UserListPartialView", response.Data);

				pib = pib.ToLower();
				var findedUser = response.Data.Where(x => x.Name.ToLower().Contains(pib) || x.Surname.ToLower().Contains(pib) || x.Patronymic.ToLower().Contains(pib)).ToList();

				if (findedUser == null || !findedUser.Any())
				{
					return BadRequest("Користувачів не знайдено");
				}
				return PartialView("_UserListPartialView", findedUser);
			}
			return View("ErrorView", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}

		[HttpPost]
		public async Task<IActionResult> Delete(int user_ID)
		{

			var response = await _userService.Delete(user_ID);
			if (response.StatusCode == ResponseStatus.Success)
			{
				return Ok(response.Description);
			}
			return BadRequest(response.Description);

		}

		[HttpGet]
		public async Task<IActionResult> Edit(int user_ID)
		{
			var response = await _userService.Get(user_ID);

			if (response.StatusCode == ResponseStatus.Success)
			{
				var register = _mapper.Map<RegisterVM>(response.Data);

				var rang = await _selectService.GetRangs();
				var position = await _selectService.GetPositions();
				var region =  _selectService.GetRegions();
				var role =  _selectService.GetRoles();

				List<SelectListItem> selectRegion = region.Data.Select(reg => new SelectListItem
				{
					Value = ((int)reg).ToString(),
					Text = reg.ToString()
				}).ToList();

				List<SelectListItem> selectRole = role.Data.Select(rol => new SelectListItem
				{
					Value = ((int)rol).ToString(),
					Text = rol.ToString()
				}).ToList();


				ViewData["Region"] = new SelectList(selectRegion.OrderBy(x => x.Text), "Value", "Text", (int)response.Data.Department.City.Region_ID);
				ViewData["Role"] = new SelectList(selectRole, "Value", "Text");
				ViewData["Rang"] = new SelectList(rang.Data, "Rang_ID", "Name");
				ViewData["Position"] = new SelectList(position.Data, "Position_ID", "Name");
				ViewData["PositionImage"] = JsonSerializer.Serialize(position.Data.Select(x => new { ID = x.Position_ID, Image = x.Image }).ToList());

				return PartialView("_UserEditPartialView", register);
			}
			return View("ErrorView", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}



		[HttpPost]
		public async Task<IActionResult> Edit(RegisterVM model)
		{
			model.Role_ID_VM = model.Position_ID_VM switch
			{
				5 => Role.Teacher,
				6 => Role.Admin,
				_ => Role.Student,
			};
			var response = await _userService.Update(_mapper.Map<User>(model));
			if (response.StatusCode == ResponseStatus.Success)
			{
				return Ok();
			}
			return BadRequest(response.Description);

		}

	}
}

SES.Web/Views/Testing/_StartingPartialView.cshtml
@model Test


<div class="d-flex flex-column">

	<div class="mb-1" style="margin-top: 1%"><a class="link_button_nodecorate" onclick="GetCatalogFilterView()"><i class="bi bi-arrow-left "></i><span>Назад</span></a></div>

	<div class="d-flex flex-row justify-content-between align-items-center">
		<div class="d-flex justify-content-start">
			<h1 class="fw-bold">Тестування за @Model.Year рік</h1>
		</div>

		<div class="d-flex justify-content-end">
			<div id="countdown"></div>
			<span style="margin-left: 30px">@Model.Position.Name</span>
		</div>
		
		
	</div>

	<div class="question-container" style="margin-top: 50px">

		<h5 style="font-weight:700; margin-bottom: 30px">Дане тестування є підготовчим і має на меті занурити працівника в умови, наближені до тих, що будуть під час проведення Державної кваліфікаційної атестації</h5>

		<div class="d-flex flex-row justify-content-between mb-2">

			<h5> <strong>Кількість часу</strong>,  відведеного для тестування цієї посади складає:</h5>

			<h5 style="font-weight: 700">@Model.Questions.Count хв</h5>

			<h5 style="font-weight: 700">Кількість питань: </h5>

			<h5 style="font-weight: 700">@Model.Questions.Count</h5>
		</div>

		<h5>Ви <strong>можете</strong> змінювати відповідь на попередні запитання</h5>

		<h5>
			Тестування буде припинено:<br>
			<ul>
				<li>коли ви будете готові і натиснете на кнопку “Завершити” до того, як закінчиться час</li> або
				<li>по завершенню наданого вам часу, при цьому буде збережено ту кількість відповідей, яку ви встигли обрати.</li>
			</ul>
		</h5>

		<h3 class="text-center" style="font-weight: 700; margin: 30px 0px;">Бажаємо вам успіхів!</h3>

		<div class="d-flex mt-4 flex-column justify-content-center align-items-center">
			<a class="main_button" onclick="TestStarting(@Model.Test_ID) " style="width: 300px; height: 40px"><span>Почати тестування</span></a>
			<a onclick="GetCatalogFilterView()" class="main_button main_button_light mt-2" style="width: 300px;height: 40px"><span>Назад</span></a>
		</div>

	</div>

</div>

<script>
	function TestStarting(test_ID) {
		$.ajax({
			url: "@Url.Action("TestStarting", "Testing")",
			type: "Get",
			data: {
				test_ID: test_ID,
			},
			success: function (data) {
				$(".question-container").html(data);
				CheckNumber();
				StartCountdown(@Model.Questions.Count);
			},
			error: function (xhr) {
				ErrorToastShow(xhr.responseText);
			}
		});
	}

	var countdown;

	function StartCountdown(seconds) {
		
		var timeInSeconds = seconds*60; 

		
		var countdownElement = document.getElementById("countdown");

		// Обновляем таймер каждую секунду
		countdown = setInterval(function () {
			if (timeInSeconds <= 0) {
				clearInterval(countdown);
				if (document.getElementById("countdown") != null){
					$.ajax({
						url: "@Url.Action("FinishTesting", "Testing")",
						type: "Get",
						success: function (data) {
							$(".question-container").html(data);
							countdownElement.innerHTML = ``;
						},
						error: function (xhr) {
							ErrorToastShow(xhr.responseText);
						}
					});
				}
			} else {
				var minutes = Math.floor(timeInSeconds / 60);
				var seconds = timeInSeconds % 60;

				var minutesStr = (minutes < 10) ? "0" + minutes : minutes;
				var secondsStr = (seconds < 10) ? "0" + seconds : seconds;
				countdownElement.innerHTML = `<span style="color: #EC6E07; font-weight: 700; font-size: 24px">${minutesStr}:${secondsStr}</span> `;
				timeInSeconds--;
			}
		}, 1000);
	}
</script>

SES.Web/Views/Testing/_TestResultPartialView.cshtml
@model Test_History



<div class="d-flex flex-column justify-content-between align-items-center" style="margin-bottom: 20px">

	@if(Model.Mark < 3)
	{
		<img width="120" height="120" src="https://cdn-icons-png.flaticon.com/512/4250/4250581.png" />

		<h1 class="text-center" style="font-weight: 700; margin-top: 40px">На жаль, ви не набрали необхідної кількості балів для успішного складання тесту!</h1>
	}
	else
	{
		<img  width="120" height="120" src="https://cdn-icons-png.flaticon.com/512/4250/4250596.png" />

		<h1 class="text-center" style="font-weight: 700; margin-top: 40px">Вітаємо з успішно складеним тестом!</h1>
	}

	<div class="d-flex flex-row" style="margin-top: 40px">
		<div class="align-items-start" style="width: 160px"><span>Ваш результат:</span></div>
		<div class="text-center" style="width: 100px"><h3 style="font-weight: 700">@Model.Right_Answer_Count/@ViewBag.QuestionCount</h3></div>
		<div class="text-end" style="width: 70px;"><span>питань</span></div>
	</div>

	<div class="d-flex flex-row" style="margin-bottom: 40px">
		<div class="align-items-start" style="width: 160px"><span>Ваша оцінка:</span></div>
		<div class="text-center" style="width: 100px"><h3 style="font-weight: 700">@Model.Mark/5</h3></div>
		<div class="text-end" style="width: 70px;"><span>балів</span></div>
	</div>

	@if (Model.Mark < 3)
	{
		<span class="text-center">Ваш результат щойно було збережено на сторінці “Кабінет” в розділі “Результати тестування”. Рекомендуємо Вам пройти цей тест ще раз для більш ретельної підготовки до Державної атестаційної кваліфікації.</span>
		
	}
	else
	{
		<span >Ваш результат щойно було збережено на сторінці “Кабінет” в розділі “Результати тестування”</span>
	}

	<div class="d-flex flex-row justify-content-around" style="margin-top: 50px">
		<a class="main_button" asp-action="Index" asp-controller="User" style="width: 300px; height: 40px"><span>В кабінет</span></a>
	</div>

</div>

SES.Web/Views/Testing/_TestingQusetionPartialView.cshtml
@model Question


<div class="container d-flex flex-column" style="width: 80%; margin-bottom: 20px">

	<h6 id="question-number">Питання @ViewBag.Number</h6>
	<h5 style="font-weight: 700; margin-bottom: 20px">@Model.Text</h5>


	@foreach (var item in Model.Options)
	{
		<div class="d-flex flex-row align-items-center" style="margin-top: 20px">
			<div>
				<input class="form-check-input answer-box" type="checkbox" id="@item.Option_ID" name="@item.Option_ID">
				<label for="@item.Option_ID"></label>
			</div>
			<div style="margin-left: 20px">
				<label class="form-check-label" for="@item.Option_ID">@item.Text</label>
			</div>
		</div>


	}

	<div class="d-flex flex-row justify-content-around" style="margin-top: 50px">
		<a onclick="PreviousQuestion()" class="main_button main_button_light" id="back_btn" style="width: 300px;height: 40px"><span>Назад</span></a>
		<a class="main_button" onclick="NextQuestion()" id="next_btn" style="width: 300px; height: 40px"><span>Далі</span></a>
		<a class="main_button" onclick="NextQuestion('Finish')" id="finish_btn" style="width: 300px; height: 40px"><span>Завершити тестування</span></a>
	</div>

</div>

<input type="hidden" id="questionAnswer" value="@ViewBag.Answer" />

<script>
	function NextQuestion(Status) {
		var selected_Options = [];

		$(".answer-box:checked").each(function () {
			selected_Options.push($(this).attr("name"));
		});
		if (selected_Options.length == 0) {
			ErrorToastShow("Оберіть варінт(-и) відповіді");
		}
		else {
			
			$.ajax({
				url: "@Url.Action("NextQuestion", "Testing")",
				type: "Get",
				data: {
					answer_option_ID: selected_Options.join(","),
					status: Status
				},
				success: function (data) {
					$(".question-container").html(data);
					if (Status == null) {
						CheckAnswer();
						CheckNumber();
					}

				},
				error: function (xhr) {
					ErrorToastShow(xhr.responseText);
				}
			});

			if (Status == "Finish") 
			{ 
				clearInterval(countdown); 
				document.getElementById("countdown").innerHTML = ``; 
			}
		}
	}

	function CheckAnswer() {
		var answer = $("#questionAnswer").val();
		if (answer != null) {
			var answerArray = answer.split(',');

			answerArray.forEach(function (item) {
				var trimmedItem = item.trim();

				var checkbox = $("input[type='checkbox'][name='" + trimmedItem + "']");

				if (checkbox.length > 0) {
					checkbox.prop('checked', true);
				}
			});
		}

	}

	function CheckNumber() {
		var number = $("#question-number").text().replace('Питання ', '').split('/');
			var back = document.getElementById("back_btn");
			var next = document.getElementById("next_btn");
			var finish = document.getElementById("finish_btn");

			if (number[0] == "1") {
				back.style.display = "none";
			}
			else back.style.display = "flex";

			if (number[0] == number[1]) {
				next.style.display = "none";
				finish.style.display = "flex";
			}
			else {
				next.style.display = "flex";
				finish.style.display = "none";
			}



	}

	function PreviousQuestion() {

		$.ajax({
			url: "@Url.Action("PreviousQuestion", "Testing")",
			type: "Get",
			success: function (data) {
				$(".question-container").html(data);
				CheckAnswer();
				CheckNumber();
			},
			error: function (xhr) {
				ErrorToastShow(xhr.responseText);
			}
		});
	}

	function FinishTesting() { }
</script>