SES.Web/Controllers/AbstractController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SES.Domain.Entity.AbstractE;
using SES.Domain.Enum;
using SES.Service.Implementations;
using SES.Service.Interfaces;
using SES.Web.Models;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Azure;

namespace SES.Web.Controllers
{
	[Authorize]
	public class AbstractController : Controller
	{

		private readonly IAbstractService _abstractService;

		public AbstractController(IAbstractService abstractService)
		{
			_abstractService = abstractService;
		}

		public ActionResult Index()
		{
			return View();
		}

		public IActionResult GetAreaOfStudy()
		{
			return PartialView("_ChoosingAreaPartialView");
		}

		public async Task<IActionResult> GetThemes(int area_ID)
		{
			var response = await _abstractService.GetAll(area_ID);
			ViewData["AreaName"] = area_ID;
			if (response.StatusCode == ResponseStatus.Success)
			{
				return PartialView("_ThemesPartialView", response.Data);
			}
			return BadRequest(response.Description);
		}

		[HttpGet]
		public IActionResult Create(int area_ID)
		{
			ViewData["AreaName"] = area_ID;
			return PartialView("_AbstractModalPartialView");

		}

		[HttpPost]
		public async Task<IActionResult> Create(Abstracts _abstract)
		{
			var response = await _abstractService.Create(_abstract);
			if (response.StatusCode == ResponseStatus.Success)
			{
				ViewData["AreaName"] = _abstract.AreaOfStudy_ID;
				return Ok(_abstract.AreaOfStudy_ID);
			}
			return BadRequest(response.Description);
		}

		[HttpGet]
		public async Task<IActionResult> Edit(int abstract_ID)
		{
			var response = await _abstractService.Get(abstract_ID);
			if (response.StatusCode == ResponseStatus.Success)
			{
				return PartialView("_AbstractEditModalPartialView", response.Data);
			}
			return View("ErrorView", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}

		[HttpPost]
		public async Task<IActionResult> Edit(Abstracts _abstract)
		{
			var response = await _abstractService.Update(_abstract);
			if (response.StatusCode == ResponseStatus.Success)
			{
				return Ok(_abstract.AreaOfStudy_ID);
			}
			return BadRequest(response.Description);
		}

		[HttpPost]
		public async Task<IActionResult> Delete(int abstract_ID, int area_ID)
		{
			if (ModelState.IsValid)
			{
				var response = await _abstractService.Delete(abstract_ID);
				if (response.StatusCode == ResponseStatus.Success)
				{
					return Ok(area_ID);
				}
				ModelState.AddModelError("", response.Description);
			}
			return BadRequest(ModelState);
		}

	}
}

SES.Web/Controllers/TestController.cs
using Azure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SES.Domain.Entity.TestE;
using SES.Domain.Enum;
using SES.Service.Implementations;
using SES.Service.Interfaces;
using SES.Web.Models;
using System.Diagnostics;
using System.Text.Json;

namespace SES.Web.Controllers
{
	public class TestController : Controller
	{
		private readonly ITestService _testService;
		private readonly ISelectService _selectService;
		private readonly IQuestionService _questionService;
		private readonly IOptionService _optionService;

		public TestController(ITestService testService, ISelectService selectService, IQuestionService questionService, IOptionService optionService)
		{
			_testService = testService;
			_selectService = selectService;
			_questionService = questionService;
			_optionService = optionService;
		}

		public IActionResult TestIndex() => View();

		[HttpGet]
		public async Task<IActionResult> GetCatalogFilterView()
		{
			var response = await _testService.Get();
			if (response.StatusCode == ResponseStatus.Success)
			{
				if (User.IsInRole("Student")) response.Data = response.Data.Where(x => x.Status == TestStatus.Підготовче).ToList();
				return PartialView("_TestFiltersPartialView", response.Data);
			}
			return View("ErrorView", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}

		[HttpGet]
		public async Task<IActionResult> GetCatalogFiltered(string year, string position, string type)
		{
			if (User.IsInRole("Student")) type = "Підготовче";
			var response = await _testService.Get();
			if (response.StatusCode == ResponseStatus.Success)
			{
				if (year != null) response.Data = ApplyYearFilter(response.Data, year.Split(','));

				if (position != null) response.Data = ApplyPositionFilter(response.Data, position.Split(','));

				if (type != null) response.Data = ApplyTypeFilter(response.Data, type.Split(','));


				if (!response.Data.Any()) return BadRequest("Результатів не знайдено");

				return PartialView("_TestCatalogPartialView", response.Data);
			}
			return View("ErrorView", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}

		[HttpGet]
		public async Task<IActionResult> TestCreate()
		{
			var position = await _selectService.GetPositions();
			ViewData["Position"] = new SelectList(position.Data, "Position_ID", "Name");
			return PartialView("_TestCreatePartialView");
		}

		[HttpPost]
		public async Task<IActionResult> TestCreate(Test model)
		{
			if (model.Status == TestStatus.Основне)
			{
				var test = await _testService.Get();
				if (test.StatusCode == ResponseStatus.Success)
				{
					if (test.Data.Any(x => x.Position_ID == model.Position_ID && x.Status == TestStatus.Основне))
					{
						return BadRequest("Основний тест для цієї посади вже існує.");
					}
				}
				else return BadRequest(test.Description);
			}

			var response = await _testService.Create(model);
			if (response.StatusCode == ResponseStatus.Success)
			{
				return Ok(new { Message = "Тест успішно створено", Test_ID = model.Test_ID });
			}
			return BadRequest(response.Description);



		}

		[HttpGet]
		public IActionResult QuestionCreate(int Test_ID)
		{
			ViewBag.Test_ID = Test_ID;
			return PartialView("_QuestionCreatePartialView");
		}

		[HttpPost]
		public async Task<IActionResult> UploadFile(IFormFile fileInput, int Test_ID)
		{
			if (fileInput != null && fileInput.Length > 0)
			{
				List<Question> questionList = new();
				try
				{
					using var streamReader = new StreamReader(fileInput.OpenReadStream());
					var fileContent = await streamReader.ReadToEndAsync();
					try
					{
						questionList = JsonSerializer.Deserialize<List<Question>>(fileContent);

					}
					catch (JsonException ex)
					{
						return BadRequest("Помилка десеріалізації JSON: " + ex.Message);
					}
					ViewBag.Test_ID = Test_ID;
					return PartialView("_QuestionCreatePartialView", questionList);
				}
				catch (Exception ex)
				{
					return BadRequest("Помилка під час читання файлу: " + ex.Message);
				}
			}
			else
			{
				return BadRequest("Виберіть файл для завантаження.");
			}
		}


		[HttpPost]
		public async Task<IActionResult> QuestionCreate(List<Question> model)
		{

			if (ModelState.IsValid)
			{
				var response = await _questionService.Create(model);
				if (response.StatusCode == ResponseStatus.Success)
				{
					return Ok(response.Description);
				}
				ModelState.AddModelError("", response.Description);
			}
			return BadRequest(ModelState);
		}

		[HttpGet]
		public async Task<IActionResult> TestEdit(int test_ID)
		{
			var position = await _selectService.GetPositions();
			ViewData["Position"] = new SelectList(position.Data, "Position_ID", "Name");

			var response = await _testService.Get(test_ID);
			if (response.StatusCode == ResponseStatus.Success)
			{
				return PartialView("_TestEditPartialView", response.Data);
			}
			return BadRequest(response.Description);
		}

		[HttpPost]
		public async Task<IActionResult> CreateOption(int question_ID)
		{
			var option = new Option() { Question_ID = question_ID, Text = string.Empty };
			var response = await _optionService.Create(option);
			if (response.StatusCode == ResponseStatus.Success)
			{
				return Ok(new { Message = "Варіант відповіді створено", Option_ID = option.Option_ID });
			}
			return BadRequest(response.Description);
		}

		[HttpPost]
		public async Task<IActionResult> DeleteOption(int option_id)
		{
			var response = await _optionService.Delete(option_id);
			if (response.StatusCode == ResponseStatus.Success)
			{
				return Ok("Варіант відповіді видалено");
			}
			return BadRequest(response.Description);
		}

		[HttpPost]
		public async Task<IActionResult> CreateQuestion(int test_ID)
		{
			var question = new Question() { Test_ID = test_ID, Text = string.Empty };
			var response = await _questionService.Create(question);
			if (response.StatusCode == ResponseStatus.Success)
			{
				var response2 = await _optionService.Get(question.Question_ID);
				if (response2.StatusCode == ResponseStatus.Success)
				{
					return Ok(new { message = "Питання успішно створено", question_ID = question.Question_ID, option_ID = response2.Data[0].Option_ID, option_ID2 = response2.Data[1].Option_ID, test_id = test_ID });
				}

				return BadRequest($"Питання створено, але з варіантами проблема :( {response2.Description}");
			}
			return BadRequest(response.Description);
		}

		[HttpPost]
		public async Task<IActionResult> DeleteQuestion(int question_id)
		{
			var response = await _questionService.Delete(question_id);
			if (response.StatusCode == ResponseStatus.Success)
			{
				return Ok("Питання видалено");
			}
			return BadRequest(response.Description);
		}

		[HttpPost]
		public async Task<IActionResult> TestEdit(Test model)
		{
			if (ModelState.IsValid)
			{
				var response = await _testService.Update(model);
				if (response.StatusCode == ResponseStatus.Success)
				{
					return Ok(response.Description);
				}
				ModelState.AddModelError("", response.Description);
			}
			return BadRequest(ModelState);
		}

		[HttpPost]
		public async Task<IActionResult> TestDelete(int test_ID)
		{
			var response = await _testService.Delete(test_ID);
			if (response.StatusCode == ResponseStatus.Success)
			{
				return Ok(response.Description);
			}
			return BadRequest(response.Description);
		}



		private static List<Test> ApplyYearFilter(List<Test> results, string[]? selectedYear) => results.Where(x => selectedYear.Contains(x.Year.ToString())).ToList();

		private static List<Test> ApplyPositionFilter(List<Test> results, string[]? selectedPosition) => results.Where(x => selectedPosition.Contains(x.Position.Name)).ToList();

		private static List<Test> ApplyTypeFilter(List<Test> results, string[]? selectedType) => results.Where(x => selectedType.Contains(x.Status.ToString())).ToList();
	}
}

SES.Web/Controllers/UserController.cs
using AutoMapper;
using Azure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SES.Domain.Entity.AbstractE;
using SES.Domain.Entity.UserE;
using SES.Domain.Enum;
using SES.Domain.ViewModel;
using SES.Service.Implementations;
using SES.Service.Interfaces;
using SES.Web.Models;
using System.Diagnostics;
using System.Text.Json;

namespace SES.Web.Controllers
{
	[Authorize]
	public class UserController : Controller
	{
		private readonly IUserService _userService;
		private readonly IMapper _mapper;
		private readonly ISelectService _selectService;

		public UserController(IUserService userService, IMapper mapper, ISelectService selectService)
		{
			_userService = userService;
			_mapper = mapper;
			_selectService = selectService;
		}

		[HttpGet]
		public IActionResult Index() => View();

		[HttpGet]
		public async Task<IActionResult> Profile()
		{
			var response = await _userService.Get(int.Parse(HttpContext.User.FindFirst("UserID").Value));
			if (response.StatusCode == ResponseStatus.Success)
			{
				return PartialView("_UserProfilePartialView", response.Data);
			}
			return View("ErrorView", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}

		[HttpPost]
		public async Task<IActionResult> Profile(User user)
		{
			var response = await _userService.Update(user);
			if (response.StatusCode == ResponseStatus.Success)
			{
				return Ok();
			}
			return BadRequest(response.Description);
		}

		[HttpGet]
		public async Task<IActionResult> GetUsersList()
		{
			var response = await _userService.Get();
			if (response.StatusCode == ResponseStatus.Success)
			{
				return PartialView("_UserListPartialView", response.Data);
			}
			return View("ErrorView", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}

		[HttpGet]
		public async Task<IActionResult> GetUsersListByName(string pib)
		{
			var response = await _userService.Get();
			if (response.StatusCode == ResponseStatus.Success)
			{
				if (pib == null) return PartialView("_UserListPartialView", response.Data);

				pib = pib.ToLower();
				var findedUser = response.Data.Where(x => x.Name.ToLower().Contains(pib) || x.Surname.ToLower().Contains(pib) || x.Patronymic.ToLower().Contains(pib)).ToList();

				if (findedUser == null || !findedUser.Any())
				{
					return BadRequest("Користувачів не знайдено");
				}
				return PartialView("_UserListPartialView", findedUser);
			}
			return View("ErrorView", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}

		[HttpPost]
		public async Task<IActionResult> Delete(int user_ID)
		{

			var response = await _userService.Delete(user_ID);
			if (response.StatusCode == ResponseStatus.Success)
			{
				return Ok(response.Description);
			}
			return BadRequest(response.Description);

		}

		[HttpGet]
		public async Task<IActionResult> Edit(int user_ID)
		{
			var response = await _userService.Get(user_ID);

			if (response.StatusCode == ResponseStatus.Success)
			{
				var register = _mapper.Map<RegisterVM>(response.Data);

				var rang = await _selectService.GetRangs();
				var position = await _selectService.GetPositions();
				var region =  _selectService.GetRegions();
				var role =  _selectService.GetRoles();

				List<SelectListItem> selectRegion = region.Data.Select(reg => new SelectListItem
				{
					Value = ((int)reg).ToString(),
					Text = reg.ToString()
				}).ToList();

				List<SelectListItem> selectRole = role.Data.Select(rol => new SelectListItem
				{
					Value = ((int)rol).ToString(),
					Text = rol.ToString()
				}).ToList();


				ViewData["Region"] = new SelectList(selectRegion.OrderBy(x => x.Text), "Value", "Text", (int)response.Data.Department.City.Region_ID);
				ViewData["Role"] = new SelectList(selectRole, "Value", "Text");
				ViewData["Rang"] = new SelectList(rang.Data, "Rang_ID", "Name");
				ViewData["Position"] = new SelectList(position.Data, "Position_ID", "Name");
				ViewData["PositionImage"] = JsonSerializer.Serialize(position.Data.Select(x => new { ID = x.Position_ID, Image = x.Image }).ToList());

				return PartialView("_UserEditPartialView", register);
			}
			return View("ErrorView", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}



		[HttpPost]
		public async Task<IActionResult> Edit(RegisterVM model)
		{
			model.Role_ID_VM = model.Position_ID_VM switch
			{
				5 => Role.Teacher,
				6 => Role.Admin,
				_ => Role.Student,
			};
			var response = await _userService.Update(_mapper.Map<User>(model));
			if (response.StatusCode == ResponseStatus.Success)
			{
				return Ok();
			}
			return BadRequest(response.Description);

		}

	}
}

SES.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - SES.Web</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/SES.Web.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
	<link rel="icon" type="image/x-icon" href="https://upload.wikimedia.org/wikipedia/commons/8/82/DSNS_emblem_2016.svg">
	<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;400&display=swap" rel="stylesheet">
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
	<header>
		<div class="container-fluid text-center header">
			<div class="container justify-content-between align-content-between align-items-center d-inline-flex p-0" style="width: 53%">

				<div class="header_btn">
					<a class="link_button" asp-action="Index" asp-controller="User">
						@if (User.Identity.IsAuthenticated)
						{
							<span>Кабінет</span>
						}
					</a>
				</div>
				<div class="header_btn">
					<a class="link_button" asp-action="Index" asp-controller="Abstract">
						@if (User.Identity.IsAuthenticated)
						{
							<span>Матеріали конспектів</span>
						}
					</a>
				</div>

				<div class="header_img"><a asp-action="Index" asp-controller="Home"><img height="80" width="80" src="https://upload.wikimedia.org/wikipedia/commons/8/82/DSNS_emblem_2016.svg" /></a></div>

				<div class="header_btn">
					@if(User.IsInRole("Teacher"))
					{
						<a class="link_button">
							@if (User.Identity.IsAuthenticated)
							{
								<span>
									Підготовчі тестування
								</span>
							}

						</a>
					}
					else
					{
						<a class="link_button" asp-action="TestIndex" asp-controller="Test">
							@if (User.Identity.IsAuthenticated)
							{
								<span>
									Підготовчі тестування
								</span>
							}

						</a>
					}
					
				</div>
				<div class="header_btn">
					<a class="link_button" asp-action="Logout" asp-controller="Account">
						@if (User.Identity.IsAuthenticated)
						{
							<span>
								Вийти
							</span>
						}
					</a>
				</div>


			</div>
		</div>
	</header>

	<div class="container p-0" style="width: 53%;">
		<main role="main" style="margin-bottom: 0px">
			@RenderBody()
		</main>
	</div>

	<footer class="footer text-center d-flex flex-wrap">
		<div class="container footer_line justify-content-between align-content-between align-items-center d-inline-flex" style="width: 53%">
			<div class="d-flex flex-column">
				<div class="footer_item d-flex align-items-center">
					<div class="footer_title"><span>ДСНС - разом і надійно!</span></div>
				</div>

				<div class="footer_item d-flex align-items-center">
					<div class="footer_icon"><img height="60" width="60" src="https://upload.wikimedia.org/wikipedia/commons/8/82/DSNS_emblem_2016.svg" /></div>
					<div class="d-flex flex-column text-start justify-content-between">
						<span>Державна служба України</span>
						<span> з надзвичайних ситуацій</span>
					</div>
				</div>
			</div>
			<div class="d-flex flex-column">
				<div class="footer_item d-flex text-start">
					<div class="footer_icon"><i class="bi bi-geo-alt"></i></div>
					<div class="d-flex flex-column text-start justify-content-between">
						<span>ГУ в місті Київ за адресою:</span>
						<a class="link_button_nodecorate" target="_blank" href="https://maps.app.goo.gl/Zi4Z3se6jdbKNEAH8">вул. О.Гончара 55-а</a>
					</div>
				</div>
				<div class="footer_item d-flex ">
					<div class="footer_icon"><i class="bi bi-clock"></i></div>
					<div class="d-flex flex-column text-start  justify-content-between">
						<span>пн-пт: 08:00 - 18:00</span>
						<span>сб-нд: 09:00 - 17:00</span>
					</div>
				</div>
			</div>
			<div class="d-flex flex-column">
				<div class="footer_item d-flex text-start">
					<div class="footer_icon"><i class="bi bi-info-circle"></i></div>
					<div class="d-flex flex-column text-start  justify-content-between">
						<span>044-202-32-11</span>
						<a href="https://dsns.gov.ua/uk" target="_blank" class="link_button_nodecorate"> kyiv.dsns.gov.ua</a>
					</div>
				</div>
				<div class="footer_item d-flex align-items-center">
					<div class="footer_icon"><i class="bi bi-envelope"></i></div>
					<div class="d-flex flex-column text-star  justify-content-betweent">
						<a class="link_button_nodecorate">kyiv@dsns.gov.ua</a>
					</div>
				</div>
			</div>
		</div>
	</footer>

	<div class="toast-container position-fixed top-0 end-0 p-3" id="toast-container" style="margin-top: 130px">
		
	</div>


	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<script>
	function SuccesToastShow(toastText) {
		let id = new Date().getTime();
		let toast = `<div class="toast custom-toast" role="alert" aria-live="assertive" data-autohide="true" aria-atomic="true" data-delay="3000" id=${id}>
					<div class="toast-header">
						<img src="https://cdn-icons-png.flaticon.com/512/6785/6785304.png" width="15" height="15" class="rounded me-2" alt="...">
						<strong class="me-auto">Успіх</strong>
					</div>
					<div class="toast-body">
							<span id="s_toastText">${toastText}</span>
					</div>
				</div>`
		let toastNode = document.createElement('div');
		toastNode.innerHTML = toast;
		document.getElementById('toast-container').appendChild(toastNode);
		$(`#${id}`).toast('show');
	}

	function ErrorToastShow(toastText) {

		let id = new Date().getTime();
		let toast = `<div class="toast custom-toast" role="alert" aria-live="assertive" data-autohide="true" aria-atomic="true" data-delay="3000" id=${id}>
						<div class="toast-header">
								<img src="https://cdn-icons-png.flaticon.com/512/463/463612.png" width="15" height="15" class="rounded me-2" alt="...">
							<strong class="me-auto">Упс</strong>
						</div>
						<div class="toast-body">
								<span id="s_toastText">${toastText}</span>
						</div>
					</div>`
		let toastNode = document.createElement('div');
		toastNode.innerHTML = toast;
		document.getElementById('toast-container').appendChild(toastNode);
		$(`#${id}`).toast('show');
	}
</script>
<style>
	.header {
		background: #03183E;
		line-height: 120px;
	}

	.header_btn {
		width: auto;
	}

	.header_img {
		width: 80px;
		height: 80px;
	}

		.header_img img {
			vertical-align: inherit;
		}

	.footer {
		height: 168px !important;
		background: var(--main-dark, #03183E);
		line-height: inherit !important;
		color: #fff;
	}

	.footer_line {
		padding: 10px;
	}

	.footer_title span {
		color: #FFF;
		font-family: 'Inter', sans-serif;
		font-size: 24px;
		font-style: normal;
		font-weight: 700;
		line-height: normal;
	}

	.footer_item {
		padding: 10px;
		height: 60px;
	}

	.footer_icon {
		font-size: 30px;
		margin-right: 10px;
	}

</style>